<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class RechargeCardsExport implements FromCollection, WithHeadings, WithMapping
{
    protected Collection $cards;

    public function __construct(Collection $cards)
    {
        $this->cards = $cards;
    }

    public function collection(): Collection
    {
        return $this->cards;
    }

    public function headings(): array
    {
        return [
            'Card Number',
            'PIN',
            'Denomination',
            'Status',
            'Generated By',
            'Assigned To',
            'Used By',
            'Generated At',
            'Used At',
            'Expires At',
        ];
    }

    public function map($card): array
    {
        return [
            $card->card_number,
            $card->pin,
            $card->denomination,
            ucfirst($card->status),
            $card->generatedBy?->name ?? 'N/A',
            $card->assignedTo?->name ?? 'N/A',
            $card->usedBy?->name ?? 'N/A',
            $card->created_at?->format('Y-m-d H:i:s') ?? 'N/A',
            $card->used_at?->format('Y-m-d H:i:s') ?? 'N/A',
            $card->expires_at?->format('Y-m-d H:i:s') ?? 'N/A',
        ];
    }
}
