<?php

declare(strict_types=1);

namespace App\Policies;

use App\Models\RechargeCard;
use App\Models\User;

class RechargeCardPolicy
{
    /**
     * Determine if the user can view any recharge cards.
     */
    public function viewAny(User $user): bool
    {
        // Only card distributors can view recharge cards
        return $user->hasRole('card-distributor');
    }

    /**
     * Determine if the user can view the recharge card.
     */
    public function view(User $user, RechargeCard $card): bool
    {
        // Card distributors can view cards assigned to them or generated by them
        return $user->hasRole('card-distributor') &&
               ($card->assigned_to === $user->id || $card->generated_by === $user->id);
    }

    /**
     * Determine if the user can create recharge cards.
     */
    public function create(User $user): bool
    {
        // Only admins and super-admins can create recharge cards
        return $user->hasAnyRole(['isp', 'super-admin', 'developer']);
    }

    /**
     * Determine if the user can update the recharge card.
     */
    public function update(User $user, RechargeCard $card): bool
    {
        // Only admins and super-admins can update recharge cards
        return $user->hasAnyRole(['isp', 'super-admin', 'developer']);
    }

    /**
     * Determine if the user can delete the recharge card.
     */
    public function delete(User $user, RechargeCard $card): bool
    {
        // Only admins and super-admins can delete recharge cards
        return $user->hasAnyRole(['isp', 'super-admin', 'developer']);
    }

    /**
     * Determine if the user can sell the recharge card.
     */
    public function sell(User $user, RechargeCard $card): bool
    {
        // Card distributor can sell cards that are:
        // 1. Assigned to them
        // 2. In 'active' status (available for sale)
        return $user->hasRole('card-distributor') &&
               $card->assigned_to === $user->id &&
               $card->status === 'active';
    }

    /**
     * Determine if the user can view transactions related to recharge cards.
     */
    public function viewTransactions(User $user): bool
    {
        // Card distributors can view their own transactions
        return $user->hasRole('card-distributor');
    }

    /**
     * Determine if the user can export sales data.
     */
    public function exportSales(User $user): bool
    {
        // Card distributors can export their own sales
        // Admins can export all sales
        return $user->hasAnyRole(['card-distributor', 'isp', 'super-admin', 'developer']);
    }
}
