@extends('panels.layouts.app')

@section('title', 'Card Details')

@section('content')
<div class="space-y-6">
    <!-- Page Header -->
    <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6">
            <div class="flex justify-between items-center">
                <div>
                    <h1 class="text-2xl font-bold text-gray-900 dark:text-gray-100">Card Details</h1>
                    <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">View recharge card information</p>
                </div>
                <a href="{{ route('panel.admin.cards.index') }}" class="inline-flex items-center px-4 py-2 bg-gray-600 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700">
                    Back to Cards
                </a>
            </div>
        </div>
    </div>

    <!-- Card Information -->
    <div class="bg-white dark:bg-gray-800 overflow-hidden shadow-sm sm:rounded-lg">
        <div class="p-6">
            <dl class="grid grid-cols-1 gap-x-4 gap-y-6 sm:grid-cols-2">
                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Card Number</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100 font-semibold">{{ $card->card_number }}</dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">PIN</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100 font-mono">{{ $card->pin }}</dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Denomination</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">{{ config('app.currency', '$') }}{{ number_format($card->denomination, 2) }}</dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Status</dt>
                    <dd class="mt-1">
                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full 
                            @if($card->status === 'active') bg-green-100 text-green-800
                            @elseif($card->status === 'used') bg-gray-100 text-gray-800
                            @elseif($card->status === 'expired') bg-red-100 text-red-800
                            @else bg-yellow-100 text-yellow-800
                            @endif">
                            {{ ucfirst($card->status) }}
                        </span>
                    </dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Generated By</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">{{ $card->generatedBy?->name ?? 'N/A' }}</dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Assigned To</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">{{ $card->assignedTo?->name ?? 'Unassigned' }}</dd>
                </div>

                @if($card->used_by)
                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Used By</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">
                        {{ $card->usedBy?->name ?? 'N/A' }}
                        @if($card->usedBy)
                            <br>
                            <span class="text-xs text-gray-500">{{ $card->usedBy->email }}</span>
                        @endif
                    </dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Used At</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">{{ $card->used_at ? $card->used_at->format('M d, Y h:i A') : 'N/A' }}</dd>
                </div>
                @endif

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Generated At</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">{{ $card->created_at->format('M d, Y h:i A') }}</dd>
                </div>

                <div>
                    <dt class="text-sm font-medium text-gray-500 dark:text-gray-400">Expires At</dt>
                    <dd class="mt-1 text-sm text-gray-900 dark:text-gray-100">{{ $card->expires_at ? $card->expires_at->format('M d, Y') : 'N/A' }}</dd>
                </div>
            </dl>
        </div>
    </div>
</div>
@endsection
