<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function dashboard() {}
    public function users() {}
    public function usersCreate() {}
    public function usersStore() {}
    public function usersEdit($id) {}
    public function usersUpdate($id) {}
    public function usersDestroy($id) {}
    public function packages() {}
    public function packagesCreate() {}
    public function packagesStore() {}
    public function packagesEdit($id) {}
    public function packagesUpdate($id) {}
    public function packagesDestroy($id) {}
    public function settings() {}
    public function ciscoDevices() {}
    public function customers() {}
    public function customersCreate() {}
    public function customersStore() {}
    public function customerImportRequests() {}
    public function bulkUpdateUsers() {}
    public function customersEdit($id) {}
    public function customersUpdate($id) {}
    public function customersPartialUpdate($id) {}
    public function customersDestroy($id) {}
    public function restoreCustomer($id) {}
    public function forceDeleteCustomer($id) {}
    public function customersSuspend($id) {}
    public function customersActivate($id) {}
    public function customersShow($id) {}
    public function deletedCustomers() {}
    public function onlineCustomers() {}
    public function offlineCustomers() {}
    public function accountTransactions() {}
    public function paymentGatewayTransactions() {}
    public function accountStatement() {}
    public function accountsPayable() {}
    public function accountsReceivable() {}
    public function incomeExpenseReport() {}
    public function expenseReport() {}
    public function expenses() {}
    public function vatCollections() {}
    public function customerPayments() {}
    public function gatewayCustomerPayments() {}
    public function operators() {}
    public function operatorsCreate() {}
    public function operatorsStore() {}
    public function operatorsEdit($id) {}
    public function operatorsUpdate($id) {}
    public function operatorsDestroy($id) {}
    public function subOperators() {}
    public function staff() {}
    public function operatorProfile($id) {}
    public function operatorSpecialPermissions($id) {}
    public function updateOperatorSpecialPermissions($id) {}
    public function loginAsOperator($operatorId) {}
    public function stopImpersonating() {}
    public function operatorWallets() {}
    public function addOperatorFunds($operator) {}
    public function storeOperatorFunds($operator) {}
    public function deductOperatorFunds($operator) {}
    public function processDeductOperatorFunds($operator) {}
    public function operatorWalletHistory($operator) {}
    public function addOperatorNttnCost($operator) {}
    public function storeOperatorNttnCost($operator) {}
    public function addOperatorBandwidthCost($operator) {}
    public function storeOperatorBandwidthCost($operator) {}
    public function operatorCostHistory($operator) {}
    public function operatorPackageRates() {}
    public function assignOperatorPackageRate($operator) {}
    public function storeOperatorPackageRate($operator) {}
    public function deleteOperatorPackageRate($operator, $package) {}
    public function operatorSmsRates() {}
    public function assignOperatorSmsRate($operator) {}
    public function storeOperatorSmsRate($operator) {}
    public function deleteOperatorSmsRate($operator) {}
    public function paymentGateways() {}
    public function paymentGatewaysCreate() {}
    public function paymentGatewaysStore() {}
    public function routers() {}
    public function routersCreate() {}
    public function routersStore() {}
    public function routersEdit($id) {}
    public function routersUpdate($id) {}
    public function routersDestroy($id) {}
    public function oltList() {}
    public function oltCreate() {}
    public function oltStore() {}
    public function oltShow($id) {}
    public function oltEdit($id) {}
    public function oltUpdate($id) {}
    public function oltDestroy($id) {}
    public function oltTestConnection($id) {}
    public function routerTestConnection($id) {}
    public function mikrotikMonitoring() {}
    public function mikrotikMonitor($id) {}
    public function mikrotikConfigure($id) {}
    public function mikrotikConfigureShow($id) {}
    public function oltDashboard() {}
    public function oltMonitor($id) {}
    public function oltPerformance($id) {}
    public function oltTemplates() {}
    public function oltSnmpTraps() {}
    public function oltFirmware() {}
    public function oltBackups() {}
    public function devices() {}
    public function deviceMonitors() {}
    public function devicesMap() {}
    public function ipv4Pools() {}
    public function ipv4PoolsCreate() {}
    public function ipv4PoolsStore() {}
    public function ipv4PoolsEdit($id) {}
    public function ipv4PoolsUpdate($id) {}
    public function ipv4PoolsDestroy($id) {}
    public function ipv4PoolsBulkDelete() {}
    public function ipv6Pools() {}
    public function ipv6PoolsCreate() {}
    public function ipv6PoolsStore() {}
    public function ipv6PoolsEdit($id) {}
    public function ipv6PoolsUpdate($id) {}
    public function ipv6PoolsDestroy($id) {}
    public function ipAnalytics() {}
    public function exportIpAnalytics() {}
    public function pppoeProfiles() {}
    public function pppoeProfilesStore() {}
    public function pppoeProfilesEdit($id) {}
    public function pppoeProfilesUpdate($id) {}
    public function pppoeProfilesDestroy($id) {}
    public function pppoeProfilesBulkDelete() {}
    public function packageFupEdit($id) {}
    public function pingTest() {}
    public function smsSend() {}
    public function smsBroadcast() {}
    public function smsHistories() {}
    public function smsEvents() {}
    public function dueDateNotification() {}
    public function paymentLinkBroadcast() {}
    public function cardsIndex() {}
    public function cardsCreate() {}
    public function cardsStore() {}
    public function cardsShow($id) {}
    public function cardsExport() {}
    public function cardsAssign() {}
    public function cardsUsedMapping() {}
    public function activityLogs() {}
    public function laravelLogs() {}
    public function schedulerLogs() {}
    public function routerLogs() {}
    public function pppLogs() {}
    public function hotspotLogs() {}
    public function radiusLogs() {}
    public function downloadInvoicePdf($invoice) {}
    public function streamInvoicePdf($invoice) {}
    public function downloadPaymentReceiptPdf($payment) {}
    public function exportInvoices() {}
    public function exportPayments() {}
    public function customerStatementPdf($customer) {}
    public function monthlyReportPdf() {}
    public function exportTransactions() {}
    public function exportVatCollections() {}
    public function exportExpenseReport() {}
    public function exportIncomeExpenseReport() {}
    public function exportReceivable() {}
    public function exportPayable() {}
}
